# Build Environment
FROM node:16-alpine3.15 as build

WORKDIR /usr/src/app

COPY package*.json .

COPY . .

RUN npm install

RUN npm run build

# Production Environment
FROM nginx:1.23.0-alpine

COPY --from=build /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
